name: IREM test

on:
  push:
    branches:
      - main

jobs:
   git_clone_test:
    runs-on: ubuntu-latest
    name: Git clone test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Repository
        uses: Sunwoo0110/IREM@v1.0.26
        with:
          github-repo-url: https://github.com/Sunwoo0110/action_IREM_test
          github-user-id: Sunwoo0110
          github-user-email: Sunwoo0110@g.skku.edu
          github-token: ${{ secrets.GH_TOKEN }}
      - name: Test finish
        run: echo "test was good"
